// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class Customer
{
    public long CustomerId { get; set; }

    public string Phone { get; set; }

    public string FullName { get; set; }

    public DateOnly? Birthday { get; set; }

    public short? Gender { get; set; }

    public int? RankId { get; set; }

    public short? Status { get; set; }

    public long? ShopId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public decimal? Spent { get; set; }

    public string Avatar { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Nfc> Nfcs { get; set; } = new List<Nfc>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Rank Rank { get; set; }

    public virtual Shop Shop { get; set; }
}