// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class Fcm
{
    public long FcmId { get; set; }

    public string FcmToken { get; set; }

    public long? UserId { get; set; }

    public virtual User User { get; set; }
}