// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class Fcm
{
    public long FcmId { get; set; }

    public long? UserId { get; set; }

    public string FcmToken { get; set; }

    public string Uniqueid { get; set; }

    public bool? Isactive { get; set; }

    public DateTime? Lastlogin { get; set; }

    public DateTime? Createdat { get; set; }

    public DateTime? Updatedat { get; set; }

    public virtual User User { get; set; }
}