// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class InventoryTransaction
{
    public long InventoryTransactionId { get; set; }

    public short? Type { get; set; }

    public long? ProductId { get; set; }

    public long? OrderId { get; set; }

    public long? UnitId { get; set; }

    public int? Quantity { get; set; }

    public string ImageUrl { get; set; }

    public decimal? Price { get; set; }

    public long? ShopId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public virtual Shop Shop { get; set; }

    public virtual Unit Unit { get; set; }
}