// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class LogActivity
{
    public long LogActivityId { get; set; }

    public long? UserId { get; set; }

    public string Content { get; set; }

    public short? Type { get; set; }

    public long? ShopId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Shop Shop { get; set; }

    public virtual User User { get; set; }
}