// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class Nfc
{
    public long NfcId { get; set; }

    public short? Status { get; set; }

    public decimal? Balance { get; set; }

    public long? CustomerId { get; set; }

    public string NfcCode { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? LastUsedDate { get; set; }

    public virtual Customer Customer { get; set; }
}