// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class Order
{
    public long OrderId { get; set; }

    public DateTime? Datetime { get; set; }

    public long? CustomerId { get; set; }

    public decimal? GrossRevenue { get; set; }

    public decimal? TotalPrice { get; set; }

    public decimal? TotalDiscount { get; set; }

    public decimal? FinalPrice { get; set; }

    public string PaymentMethod { get; set; }

    public short? Status { get; set; }

    public long? ShiftId { get; set; }

    public long? ShopId { get; set; }

    public long? VoucherId { get; set; }

    public decimal? Discount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Note { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<InventoryTransaction> InventoryTransactions { get; set; } = new List<InventoryTransaction>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Shift Shift { get; set; }

    public virtual Shop Shop { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual Voucher Voucher { get; set; }
}