// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class Product
{
    public long ProductId { get; set; }

    public long? CategoryId { get; set; }

    public string ProductName { get; set; }

    public int? Quantity { get; set; }

    public bool? IsLow { get; set; }

    public decimal? Cost { get; set; }

    public decimal? Price { get; set; }

    public string ImageUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public string Barcode { get; set; }

    public decimal? Discount { get; set; }

    public short? Status { get; set; }

    public long? UnitIdFk { get; set; }

    public long? ShopId { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<InventoryTransaction> InventoryTransactions { get; set; } = new List<InventoryTransaction>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<ProductUnit> ProductUnits { get; set; } = new List<ProductUnit>();

    public virtual ICollection<PromotionProduct> PromotionProducts { get; set; } = new List<PromotionProduct>();

    public virtual ICollection<ReportDetail> ReportDetails { get; set; } = new List<ReportDetail>();

    public virtual Shop Shop { get; set; }

    public virtual Unit UnitIdFkNavigation { get; set; }
}