// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class ProductUnit
{
    public long ProductUnitId { get; set; }

    public long? ProductId { get; set; }

    public long? UnitId { get; set; }

    public decimal? ConversionFactor { get; set; }

    public decimal? Price { get; set; }

    public long? ShopId { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Product Product { get; set; }

    public virtual Shop Shop { get; set; }

    public virtual Unit Unit { get; set; }
}