// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class PromotionProduct
{
    public long PromotionProductId { get; set; }

    public long PromotionId { get; set; }

    public long ProductId { get; set; }

    public long UnitId { get; set; }

    public virtual Product Product { get; set; }

    public virtual Promotion Promotion { get; set; }

    public virtual Unit Unit { get; set; }
}