// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class Rank
{
    public int RankId { get; set; }

    public string RankName { get; set; }

    public double? Benefit { get; set; }

    public double? Threshold { get; set; }

    public long ShopId { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual Shop Shop { get; set; }
}