// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class Report
{
    public long ReportId { get; set; }

    public short? Type { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public DateTime? CreateAt { get; set; }

    public decimal? Revenue { get; set; }

    public int? OrderCounter { get; set; }

    public long? ShopId { get; set; }

    public decimal? GrossProfit { get; set; }

    public decimal? Cost { get; set; }

    public virtual ICollection<ReportDetail> ReportDetails { get; set; } = new List<ReportDetail>();

    public virtual Shop Shop { get; set; }
}