// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class ReportDetail
{
    public long ReportDetailId { get; set; }

    public long? ReportId { get; set; }

    public long? ProductId { get; set; }

    public int? Quantity { get; set; }

    public virtual Product Product { get; set; }

    public virtual Report Report { get; set; }
}