// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class Shift
{
    public long ShiftId { get; set; }

    public long? UserId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? ClosedDate { get; set; }

    public short? Status { get; set; }

    public decimal? Revenue { get; set; }

    public decimal? OpeningCash { get; set; }

    public long? ShopId { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Shop Shop { get; set; }

    public virtual User User { get; set; }
}