// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class ShopSubscription
{
    public long ShopSubscriptionId { get; set; }

    public long? ShopId { get; set; }

    public long? PlatformProductId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public short? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Shop Shop { get; set; }
}