// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class Transaction
{
    public long TransactionId { get; set; }

    public long? OrderId { get; set; }

    public long? UserId { get; set; }

    public string PaymentStatus { get; set; }

    public string AppTransId { get; set; }

    public string ZpTransId { get; set; }

    public int? ReturnCode { get; set; }

    public string ReturnMessage { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual User User { get; set; }
}