// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class UserFeature
{
    public long UserFeatureId { get; set; }

    public long? UserId { get; set; }

    public long FeatureId { get; set; }

    public string FeatureName { get; set; }

    public bool? IsEnabled { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User User { get; set; }
}