// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class User
{
    public long UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public short? Status { get; set; }

    public long? ShopId { get; set; }

    public short? Role { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Avatar { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual ICollection<Fcm> Fcms { get; set; } = new List<Fcm>();

    public virtual ICollection<LogActivity> LogActivities { get; set; } = new List<LogActivity>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual Shop Shop { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual ICollection<UserFeature> UserFeatures { get; set; } = new List<UserFeature>();
}