// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class Voucher
{
    public long VoucherId { get; set; }

    public decimal? Value { get; set; }

    public DateTime? CreatedAt { get; set; }

    public short? Type { get; set; }

    public DateTime? Expired { get; set; }

    public long? ShopId { get; set; }

    public string Code { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Shop Shop { get; set; }
}