// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_TENANT_REPO.Models;

public partial class Zalopay
{
    public long ZalopayId { get; set; }

    public long? ShopId { get; set; }

    public string AppId { get; set; }

    public string Key1 { get; set; }

    public string Key2 { get; set; }

    public string CallbackUrl { get; set; }

    public short? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Shop Shop { get; set; }
}